@extends('layouts.sidebar2')

@section('content')

<h1> Campagne aanmaken</h1>

<div class="EditCampaignForm">
    Zet een marketingcampagne op voor je merk om influencers en publishers je product of dienst te laten promoten onder hun doelgroep. Bij aanmaken van deze  campagne is die terug te vinden  bij concepten. Hulp nodig? Bekijk dan Deze tutorial.
<div class="Introductie" style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Introductie
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Naam
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Marketingdoel
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Matching
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Kanalen
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Producten
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Briefing
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Voorwarden
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Doelgroep
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 2255);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    vergoedingsmodel
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    Uitsluiten
</div>
<div style="width:1600px;background-attachment: scroll;background-clip: border-box;background-color: rgb(, 225, 225);	background-repeat: repeat;background-size: auto;border-bottom-color: rgb(255, 255, 255);border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;border-bottom-style: none;border-bottom-width: 0px;border-image: repeat;border-image-slice: 100%;border-image-source: none;border-left-color: rgb(255, 255, 255);border-left-style: none;border-left-width: 0px;border-right-color: rgb(255, 255, 255);border-right-style: none;border-right-width: 0px;border-top-color: rgb(255, 255, 255);box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 2px 0px, rgba(0, 0, 0, 0.14) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;color:rgb(0, 0, 0);cursor: pointer;display: inline-block;font-size: 14px;font-weight: 500;height: 36px;overflow:hidden;position: relative;text-decoration: rgb(255, 255, 255);text-decoration-color: rgb(255, 255, 255);text-decoration-line: none;text-decoration-style:none;text-transform: uppercase;transition-delay: 0s, 0s;transition-duration: 0.3s,0.3s;transition-property: background-color, color;transition-timing-function: ease, ease;">
    bevestigen
</div>


</div>

@endsection